name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          log-level: verbose
          exclude: |
            **/RoleMiddleware.php
            **/2026_03_07_102249_create_activity_log_table.php
            **/database/migrations/2026_03_07_102250_add_event_column_to_activity_log_table.php
            **/database/migrations/2026_03_07_102251_add_batch_uuid_column_to_activity_log_table.php
            **/debug_profile.png
            **/fb_results.json
            **/fb_session
            **/ig_session
         #server-dir: /   # ⚠️ IMPORTANT
         
